//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSBCR.modele
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gsb_visite_groupe3Entities : DbContext
    {
        public gsb_visite_groupe3Entities()
            : base("name=gsb_visite_groupe3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FAMILLE> FAMILLE { get; set; }
        public DbSet<MEDICAMENT> MEDICAMENT { get; set; }
        public DbSet<MOTIF_VISITE> MOTIF_VISITE { get; set; }
        public DbSet<OFFRIR> OFFRIR { get; set; }
        public DbSet<POSSEDER> POSSEDER { get; set; }
        public DbSet<PRATICIEN> PRATICIEN { get; set; }
        public DbSet<RAPPORT_VISITE> RAPPORT_VISITE { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<SECTEUR> SECTEUR { get; set; }
        public DbSet<SPECIALITE> SPECIALITE { get; set; }
        public DbSet<TRAVAILLER> TRAVAILLER { get; set; }
        public DbSet<TYPE_PRATICIEN> TYPE_PRATICIEN { get; set; }
        public DbSet<VISITEUR> VISITEUR { get; set; }
        public DbSet<VAFFECTATION> VAFFECTATION { get; set; }
    }
}
